#!/bin/bash

git diff --cached --name-only --diff-filter=ACMRT | grep "\.\(cpp\|h\|hpp\|c\)$" | xargs -n1 clang-format -style=file -fallback-style=None -sort-includes -output-replacements-xml | grep "<replacement " >/dev/null

if [ $? -ne 1 ]
then
    echo "Clang-format check failed for modified files"
    exit 1;
fi

