#!/bin/bash

git diff --cached --name-only --diff-filter=ACMRT \
    | grep "\.\(h\|hh\|hpp\|c\|cpp\)$" \
    | xargs -n 1 clang-format -style=file -fallback-style=None -sort-includes -output-replacements-xml \
    | grep "<replacement " > /dev/null

if [ $? -ne 1 ]
then
    echo "Clang-format check failed for modified files"
    exit 1;
fi

