#!/usr/bin/env bash

# Set bash to vi - Mode
set -o vi

# Set caps as additional escape
if [ -f /usr/bin/setxkbmap ]; then
    /usr/bin/setxkbmap -option "caps:escape"
fi

# disable software flow control
stty -ixon

# Add `~/bin` to the `$PATH`
export PATH="$PATH:$HOME/bin"

# Load the shell dotfiles, and then some:
# ~/bashrc.local can be used for other settings you don’t want to commit.
for file in ~/.bash/{prompt,exports,aliases} ~/.bashrc.local; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
#shopt -s checkwinsize

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null
done

# Add tab completion for many Bash commands
if [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
fi

# Enable tab completion for `g` by marking it as an alias for `git`
if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
    complete -o default -o nospace -F _git g
fi

# Add `killall` tab completion for common apps
complete -o "nospace" -W "firefox sl" killall

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if [ -f ~/.dir_colors/dircolors ]
    then eval `dircolors ~/.dir_colors/dircolors`
fi
